version: 2.1
jobs:
  test_code:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            main.py

workflows:
  version: 2
  main:
    jobs:
      - test_code
