name: Téléchargement et Publication des données DECP

on:
  schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 139bercy/decp
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Dépendances
      run: pip install pandas datetime wget xmltodict regex pytest-shutil dict2xml
    -
      name: Process
      run: python main.py
    -
      name: test 
      run: cd results/ && ls
