name: Téléchargement et Publication des données DECP

on:
  schedule:
      - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: 139bercy/decp
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Dépendances
      run: pip install pandas datetime wget xmltodict regex pytest-shutil dict2xml
    -
      name: Process
      run: python main.py
    -
      name: Publication
      run: lftp -u opendatamef:xeib9foothiz4chi fr.ftp.opendatasoft.com -e "set ftp:ssl-force true ; set ssl:verify-certificate false; cd decp; cd test; put results/decp.json ; quit"

